package com.phairplay.service

/**
 * PhairPlayService stub for JVM test compilation.
 *
 * The real PhairPlayService extends android.app.Service and depends on
 * NotificationCompat (AndroidX) and the R resource class (generated by AGP),
 * neither of which are available in the standalone JVM test runner.
 *
 * This stub provides only the companion object constants that are needed by
 * ServiceController (at compile time) and ServiceControllerTest / PhairPlayServiceTest
 * (at test time). No Android lifecycle methods are present.
 */
class PhairPlayService {
    companion object {
        const val ACTION_START   = "com.phairplay.action.START"
        const val ACTION_STOP    = "com.phairplay.action.STOP"
        const val ACTION_RESTART = "com.phairplay.action.RESTART"
        const val NOTIFICATION_ID = 1
        const val CHANNEL_ID     = "phairplay_service"
    }
}
